on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4             # updated from v2 to v3
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2 # latest stable version as per repo (v1 se v2 hai)
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4       # updated from v2 to v3
        with:
          name: package
          path: ./bin/*.apk
